# Site settings
title: Angelos Nikolas 
description: 'Business Card Page'
url: 'https://angelosnikolas.github.io/'
baseurl: ''
profilepic: '/images/me3.jpg'
bkimage: '/images/bk1.jpg'
font_awesome: '3056cb4866.js'

author:
  name: 'Angelos Nikolas'
  email: a.nikolas.net@gmail.com
  github_username:  AngelosNikolas
  linkedin_username:  angelos-nikolas-33a7b1236
  

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
